#!/usr/bin/env python3
import os
import json
import requests


# get the credentials for your TFC environment
home_directory = os.environ["HOME"]
file = open(home_directory + '/.terraform.d/credentials.tfrc.json')

# get the token data
data = json.load(file)
token = (data["credentials"]["app.terraform.io"]["token"])

# get the variables from terraform cloud
headers = {
    'Authorization': f"Bearer {token}",
    'Content-Type': 'application/vnd.api+json',
}

workspace_url = "https://app.terraform.io/api/v2/organizations/patrickmunne/varsets"
response = requests.get(workspace_url, headers=headers)
data = response.json()

# make it pretty
pretty_json = json.dumps(data, indent=2)

# print the json output
print(pretty_json)
  
# Closing file
file.close()