#!/usr/bin/env python3
import os
import json
import requests

def get_token():
    # get the credentials for your TFC environment
    home_directory = os.environ["HOME"]
    file = open(home_directory + '/.terraform.d/credentials.tfrc.json')

    # get the token data
    data = json.load(file)
    token = (data["credentials"]["app.terraform.io"]["token"])
    
    # Closing file
    file.close()
    return token

# token = get_token()

def header(token, organization, varset_name):
    # get the variables from terraform cloud
    headers = {
        'Authorization': f"Bearer {token}",
        'Content-Type': 'application/vnd.api+json',
    }

    workspace_url = "https://app.terraform.io/api/v2/organizations/" + organization + "/varsets"
    response = requests.get(workspace_url, headers=headers)
    data = response.json()
    varsets = data["data"]
    
    for varset in varsets:
        if varset["attributes"]["name"] == varset_name:
            return(json.dumps(varset["attributes"], indent=2))
            


# Get the values
organization_name = str(input("organization name? (default: patrickmunne) : ") or "patrickmunne")
varset_name     = str(input("For which varset name do you want details? (default: lotte_test) : ") or "lotte_test")

print(header(get_token(), organization_name, varset_name))
  